/* Canvas-free text measurement for the nyuchi/banner SVG engines.
 *
 * The engines normally measure text with a canvas 2d context
 * (`ctx.measureText`), which does not exist in Cloudflare Workers. This
 * module measures the same way a font renderer would: by summing the
 * per-character advance widths extracted from the actual font files
 * (see ./font-metrics.ts, generated by scripts/extract-font-metrics.mjs).
 *
 * `measureWithMetrics(text, font)` accepts the same CSS font shorthand
 * strings the engines build for canvas (e.g. `700 42px "Noto Serif",serif`)
 * so it can be dropped in as a fallback inside the engines' private
 * `measure()` helpers.
 */

import { FONT_METRICS, FONT_FALLBACK_AVG } from './font-metrics'

export { FONT_METRICS, FONT_FALLBACK_AVG }

interface ParsedFont {
  family: string
  weight: number
  size: number
}

/* Available weights per family, derived once from the table keys. */
const FAMILY_WEIGHTS: Record<string, number[]> = {}
for (const key of Object.keys(FONT_METRICS)) {
  const idx = key.lastIndexOf(':')
  const family = key.slice(0, idx)
  const weight = Number(key.slice(idx + 1))
  ;(FAMILY_WEIGHTS[family] ??= []).push(weight)
}
for (const family of Object.keys(FAMILY_WEIGHTS)) {
  FAMILY_WEIGHTS[family].sort((a, b) => a - b)
}

const DEFAULT_FAMILY = 'Noto Sans'

/** Parse the CSS font shorthand the engines build: `[style] [weight] <size>px <family-list>`. */
export function parseFontString(font: string): ParsedFont {
  const m = /^\s*(?:(?:normal|italic|oblique)\s+)?(?:(\d{3}|bold|normal)\s+)?([\d.]+)px\s+(.+)$/.exec(
    font,
  )
  if (!m) return { family: DEFAULT_FAMILY, weight: 400, size: 16 }
  const rawWeight = m[1]
  const weight = rawWeight === 'bold' ? 700 : rawWeight === 'normal' || !rawWeight ? 400 : Number(rawWeight)
  const size = parseFloat(m[2])
  /* First family in the list, quotes stripped. */
  const family = m[3].split(',')[0].trim().replace(/^["']|["']$/g, '')
  return { family, weight, size }
}

/** Pick the nearest weight we have metrics for. */
function nearestWeight(family: string, weight: number): number {
  const available = FAMILY_WEIGHTS[family]
  let best = available[0]
  for (const w of available) {
    if (Math.abs(w - weight) < Math.abs(best - weight)) best = w
  }
  return best
}

/**
 * Measure `text` rendered with the CSS `font` string, in px.
 * Unknown families fall back to Noto Sans; unknown characters use the
 * per-font average advance width.
 */
export function measureWithMetrics(text: string, font: string): number {
  const parsed = parseFontString(font)
  const family = FAMILY_WEIGHTS[parsed.family] ? parsed.family : DEFAULT_FAMILY
  const key = `${family}:${nearestWeight(family, parsed.weight)}`
  const widths = FONT_METRICS[key]
  const fallback = FONT_FALLBACK_AVG[key]
  let em = 0
  for (const ch of text) {
    em += widths[ch] ?? fallback
  }
  return em * parsed.size
}
