//! The pack: what a build produces, and what publish (headless or through
//! the MCP tools) sends.
//!
//! `out/` beside the release file holds the three images, the generated
//! `campaign.toml` they were rendered from, the imaging `manifest.json`
//! (alt text per image) and `pack.json` — the Sanity draft document and one
//! Postiz draft per channel, ready to send as they are.

use crate::channels::{Channel, Channels};
use crate::spec::{Images, Loaded, Override};
use serde::Serialize;
use serde_json::{Value, json};

#[derive(Debug, Serialize)]
pub struct Pack {
    pub slug: String,
    pub brand: String,
    pub tracking_issue: String,
    pub live: Vec<String>,
    pub sanity: SanityDraft,
    pub posts: Vec<PostizDraft>,
}

#[derive(Debug, Serialize)]
pub struct SanityDraft {
    pub project: String,
    pub dataset: String,
    /// The published id; the draft is `drafts.<document_id>`.
    pub document_id: String,
    pub studio_url: String,
    pub public_url: String,
    /// The document without `heroImage` (the asset is uploaded first).
    pub document: Value,
    pub hero_file: String,
    pub hero_alt: String,
}

#[derive(Debug, Serialize)]
pub struct PostizDraft {
    pub channel: String,
    pub name: String,
    pub platform: String,
    pub integration: String,
    /// The post as Postiz takes it: one `<p>` per line.
    pub html: String,
    pub settings: serde_json::Map<String, Value>,
    pub image_file: String,
    pub image_alt: String,
}

/// The rendered image set for a release: one campaign, three presets.
pub fn campaign_toml(images: &Images, theme: &str) -> String {
    let mut t = toml::Table::new();
    t.insert("theme".into(), theme.into());
    t.insert(
        "mode".into(),
        if images.dark { "dark" } else { "light" }.into(),
    );
    t.insert("out".into(), ".".into());
    let mut privacy = toml::Table::new();
    // No screenshot: only text and the logo are drawn.
    privacy.insert("fake_or_redacted".into(), false.into());
    t.insert("privacy".into(), privacy.into());
    let mut content = toml::Table::new();
    if let Some(e) = &images.eyebrow {
        content.insert("eyebrow".into(), e.clone().into());
    }
    content.insert("headline".into(), images.headline.clone().into());
    if let Some(s) = &images.sub {
        content.insert("sub".into(), s.clone().into());
    }
    content.insert(
        "points".into(),
        toml::Value::Array(images.points.iter().map(|p| p.clone().into()).collect()),
    );
    if let Some(c) = &images.cta {
        content.insert("cta".into(), c.clone().into());
    }
    t.insert("content".into(), content.into());

    let mut renders = Vec::new();
    for (preset, o) in [
        ("og", &images.og),
        ("square", &images.square),
        ("story", &images.story),
    ] {
        let mut r = toml::Table::new();
        r.insert("preset".into(), preset.into());
        r.insert("file".into(), format!("{preset}.png").into());
        if let Some(Override {
            headline,
            sub,
            points,
            dark,
        }) = o
        {
            if let Some(h) = headline {
                r.insert("headline".into(), h.clone().into());
            }
            if let Some(s) = sub {
                r.insert("sub".into(), s.clone().into());
            }
            if let Some(p) = points {
                r.insert(
                    "points".into(),
                    toml::Value::Array(p.iter().map(|p| p.clone().into()).collect()),
                );
            }
            if let Some(d) = dark {
                r.insert("mode".into(), if *d { "dark" } else { "light" }.into());
            }
        }
        renders.push(toml::Value::Table(r));
    }
    t.insert("render".into(), toml::Value::Array(renders));
    format!(
        "# Generated by nyuchi-release from release.toml. Do not edit: edit [images] there.\n\n{}",
        toml::to_string(&t).expect("a campaign serialises")
    )
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Plain text to Postiz HTML: one `<p>` per non-empty line.
pub fn to_html(text: &str) -> String {
    text.lines()
        .map(str::trim_end)
        .filter(|l| !l.trim().is_empty())
        .map(|l| format!("<p>{}</p>", esc(l)))
        .collect()
}

fn settings(ch: &Channel) -> serde_json::Map<String, Value> {
    let mut m = serde_json::Map::new();
    m.insert("__type".into(), Value::String(ch.platform.clone()));
    for (k, v) in &ch.settings {
        m.insert(
            k.clone(),
            serde_json::to_value(v).expect("toml values convert"),
        );
    }
    m
}

/// Build the pack. `alts` maps an image name (`og`, `square`, `story`) to
/// its alt text from the imaging manifest.
pub fn build(l: &Loaded, channels: &Channels, alts: &dyn Fn(&str) -> String) -> Pack {
    let r = &l.release;
    let target = &channels.brand[&r.brand].sanity;
    let id = crate::document_id(&r.slug);
    let post_slug = r.post_slug();
    let mut doc = json!({
        "_type": target.doc_type,
        "title": r.post.title,
        "slug": { "_type": "slug", "current": post_slug },
        "description": r.post.description,
        "author": { "_type": "reference", "_ref": target.author },
        "pubDate": format!("{}T08:00:00.000Z", r.post.date),
        "tags": r.post.tags,
        "featured": false,
        "body": l.body.trim_end().to_string() + "\n",
    });
    if let Some(a) = &r.post.audience {
        doc["audience"] = json!(a);
    }
    if let Some(c) = &r.post.category {
        doc["category"] = json!({ "_type": "reference", "_ref": c });
    }
    let sanity = SanityDraft {
        project: target.project.clone(),
        dataset: target.dataset.clone(),
        studio_url: format!(
            "{}/intent/edit/id={id};type={}",
            target.studio.trim_end_matches('/'),
            target.doc_type
        ),
        public_url: format!("{}{post_slug}", target.public_prefix),
        document_id: id,
        document: doc,
        hero_file: "og.png".into(),
        hero_alt: alts("og"),
    };
    let posts = r
        .socials
        .iter()
        .filter_map(|s| {
            let ch = channels.get(&s.channel)?;
            Some(PostizDraft {
                channel: ch.key.clone(),
                name: ch.name.clone(),
                platform: ch.platform.clone(),
                integration: ch.integration.clone(),
                html: to_html(&s.text),
                settings: settings(ch),
                image_file: format!("{}.png", s.image),
                image_alt: alts(&s.image),
            })
        })
        .collect();
    Pack {
        slug: r.slug.clone(),
        brand: r.brand.clone(),
        tracking_issue: r.tracking_issue.clone(),
        live: r.live.clone(),
        sanity,
        posts,
    }
}
